name: Pylint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5          # v5 knows about the newest versions
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint

      - name: Run Pylint using project pylintrc
        run: |
          # If your pylintrc is in the repo root and named .pylintrc or pylintrc,
          # the next line is enough.
          pylint --fail-under=8 $(git ls-files '*.py')
          # If the config lives elsewhere, comment the line above and uncomment the next one:
          # pylint --rcfile path/to/your/pylintrc --fail-under=8 $(git ls-files '*.py')
