name: Pylint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]   # add others when needed

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint

      - name: Run Pylint
        run: |
          # If .pylintrc / pylintrc is at repo root it’s auto‑loaded.
          # Adjust --fail-under to the minimum score you’ll accept.
          pylint --fail-under=8 $(git ls-files '*.py')
